---
team_id: '32'
team_name: 'Manchester United'
short_name: 'Man Utd'
country: 'England'
league: 'Premier League'
season_start: '2020'
season_end: '2021'
browser: 'Chrome'
timeout: '222'
cache: ''
summary_only: 'false'
fixtures_only: 'false'
