---
team_id: '32'
team_name: 'Manchester United'
short_name: 'Man Utd'
country: 'England'
league: 'Premier League'
season_start: '2022'
season_end: '2023'
browser: 'Chrome'
timeout: '222'
ws_cache_url: ''
tus_ratings_url: 'https://www.theunitedstand.com/articles/match-ratings'
summary_only: 'false'
fixtures_only: 'false'
read_in_bulk: 'true'
read_in_reverse: 'false'
