const DATA = [
  {
    id: 1,
    name: 'Human-Aware Planning and Explainable AI',
    link: null,
    image: 'xai',
    primary: true,
    secondary: false,
    tertiary: false,
    tags: ['xai', 'humanai'],
  },
  {
    id: 2,
    name: 'Process Design',
    link: null,
    image: 'process',
    primary: false,
    secondary: true,
    tertiary: false,
    tags: ['bpm'],
  },
  {
    id: 3,
    name: 'Mixed Reality',
    link: null,
    image: 'vamhri',
    primary: false,
    secondary: true,
    tertiary: false,
    tags: ['vamhri'],
  },
  {
    id: 5,
    name: 'NLC2CMD @ NeurIPS',
    link: 'https://ibm.biz/nlc2cmd',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 6,
    name: 'XAIP @ ICAPS',
    link: 'https://ibm.biz/xaip2020',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 7,
    name: 'VAM-HRI @ HRI',
    link: 'http://vam-hri.xyz/',
    image: null,
    primary: false,
    secondary: false,
    tertiary: true,
  },
  {
    id: 4,
    name: 'Learn More',
    link: 'https://github.com/IBM/clai',
    image: 'clai',
    primary: false,
    secondary: false,
    tertiary: true,
  },
];

export default DATA;
